name: "Build Scope Analyzer"
description: "Analyze git diff to identify what needs to be built and generate strategy matrix"
author: "Stratus Team"

inputs:
  root-path:
    description: "Root path to search for changes (defaults to /github/workspace)"
    required: false
    default: /github/workspace
  include-pattern:
    description: 'Pattern for paths to include (substring matching, e.g., "src")'
    required: false
    default: "*"
  exclude-pattern:
    description: 'Pattern for paths to exclude (substring matching, e.g., "test")'
    required: false
    default: ""
  comparison_ref:
    description: "Git ref to compare against (defaults to automatic detection)"
    required: false
    default: ""

outputs:
  matrix:
    description: |
      Complete JSON matrix structure with all app and container information.

      Use jq to extract specific arrays from this output:
      - .apps.updated: Changed apps that need building/deployment
      - .apps.all: All discovered apps (changed + unchanged)
      - .apps.deleted: Deleted apps that need cleanup
      - .containers.updated: Changed containers that need building
      - .containers.all: All discovered containers
      - .containers.deleted: Deleted containers that need cleanup

      Example extraction in workflow:
        MATRIX_JSON='${{ steps.analyze.outputs.matrix }}'
        echo "apps_updated=$(echo $MATRIX_JSON | jq -c '.apps.updated')" >> $GITHUB_OUTPUT

      Full structure:
      {
        "apps": {
          "updated": [...],     # Apps with changes
          "all": [...],         # All discovered apps
          "deleted": [...],     # Deleted apps
          "has_updates": bool,  # True if any apps changed
          "has_deletions": bool # True if any apps deleted
        },
        "containers": {
          "updated": [...],     # Containers with changes
          "all": [...],         # All discovered containers
          "deleted": [...],     # Deleted containers
          "has_updates": bool,  # True if any containers changed
          "has_deletions": bool # True if any containers deleted
        },
        "comparison_ref": "origin/main" # Git ref used for comparison
      }
  comparison_ref:
    description: "Git ref used for comparison (also available in matrix.comparison_ref)"

runs:
  using: "docker"
  image: "docker://ghcr.io/stratus-test/stratus-actions/build-scope-analyzer:v1.0.11"
  args:
    - "--root-path"
    - "${{ inputs.root-path }}"
    - "--include-pattern"
    - "${{ inputs.include-pattern }}"
    - "--exclude-pattern"
    - "${{ inputs.exclude-pattern }}"
    - "--comparison-ref"
    - "${{ inputs.comparison_ref }}"
