name: "Build Scope Analyzer"
description: "Analyze git diff to identify what needs to be built and generate strategy matrix"
author: "Stratus Team"

inputs:
  root-path:
    description: "Root path to search for changes (defaults to GITHUB_WORKSPACE)"
    required: false
    default: ${{ github.workspace }}
  include-pattern:
    description: 'Glob pattern for paths to include (e.g., "apps/*")'
    required: false
    default: "*"
  exclude-pattern:
    description: 'Glob pattern for paths to exclude (e.g., "docs/*")'
    required: false
    default: ""
  ref:
    description: "Git ref to compare against (defaults to automatic detection)"
    required: false
    default: ""

outputs:
  matrix:
    description: |
      Clean, focused JSON matrix structure with the following sub-properties:

      - matrix.apps: Container app deployment information
        - matrix.apps.updated: Array of changed apps with app.yaml/app.yml
        - matrix.apps.all: Array of all apps with app.yaml/app.yml
        - matrix.apps.deleted: Array of deleted apps
        - matrix.apps.has_updates: Boolean indicating if any apps were changed
        - matrix.apps.has_deletions: Boolean indicating if any apps were deleted

      - matrix.containers: Docker container build information
        - matrix.containers.updated: Array of changed containers, each with:
            - path: App folder path
            - context: Docker build context (from @context or defaults to app folder)
            - app_name: App name
            - dockerfile: Dockerfile info (path, name, suffix)
            - image_name: Image name for tagging
            - container_name: Canonical container name
        - matrix.containers.all: Array of all containers (same structure as above)
        - matrix.containers.deleted: Array of deleted containers
        - matrix.containers.has_updates: Boolean indicating if any containers were changed
        - matrix.containers.has_deletions: Boolean indicating if any containers were deleted

      - matrix.ref: Git ref used for comparison
  ref:
    description: "Git ref used for comparison"

env:
  GITHUB_ORG_LOWER_CASE: "stratus-test"

runs:
  using: "docker"
  image: "docker://ghcr.io/stratus-test/stratus-gh-actions/build-scope-analyzer:latest"
  args:
    - "--root-path"
    - "${{ inputs.root-path }}"
    - "--include-pattern"
    - "${{ inputs.include-pattern }}"
    - "--exclude-pattern"
    - "${{ inputs.exclude-pattern }}"
    - "--ref"
    - "${{ inputs.ref }}"
